language: node_js
node_js:
  - stable
install:
  - npm install

after_script:

jobs:
  include:
    - stage: Compile
      script: npm run build-linux
    - stage: Unit tests
      script: npm run test
      after_script: npm run ci-process-cover

