language: node_js

node_js:
  - stable

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm ci

script:
  - npm run build-linux
  - npm run test

after_script:
  - npm run ci-process-cover

