language: node_js

node_js:
  - stable

install:
  - npm ci

cache:
  directories:
    - "$HOME/.npm"

jobs:
  include:
    - stage: compile
      script: npm run build-linux
    - stage: test
      script: npm run test

after_script:
  - npm run ci-process-cover
